update jenlinsfile 1.0

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -1,87 +1,90 @@
 pipeline {
-  agent any
+    agent any
 
-  environment {
-    CLICKHOUSE_JDBC_VERSION = '0.6.4-patch21'
-    SPARK_VERSION          = '3.5.5'          // ваша версия Spark
-    SCALA_VERSION          = '2.12'           // ваша версия Scala
-    WORKDIR                = "${env.WORKSPACE}"
-  }
-
-  stages {
-    stage('Checkout') {
-      steps {
-        checkout scm
-      }
+    environment {
+        // Путь до Spark, если установлено в переменной SPARK_HOME на агенте
+        SPARK_HOME = "${env.SPARK_HOME ?: '/opt/homebrew/bin'}"
+        JDBC_JAR = 'clickhouse-jdbc-all.jar'
     }
 
-    stage('Start Docker Services') {
-      steps {
-        sh 'docker-compose up -d'
-        sh 'sleep 15'
-      }
-    }
-
-    stage('Init MySQL') {
-      steps {
-        sh '''
-          docker exec project-mysql-1 bash -c "mysql -uroot -proot bank < /sql/init_mysql.sql" || true
-        '''
-      }
-    }
-
-    stage('Register Debezium') {
-      steps {
-        sh '''
-          curl -X POST http://localhost:8083/connectors \
-            -H "Content-Type: application/json" \
-            --data-binary @debezium-connector.json || true
-        '''
-      }
-    }
-
-    stage('Prepare JARs') {
-      steps {
-        dir("${WORKDIR}") {
-          sh '''
-            # Загрузим ClickHouse JDBC все-в-одном
-            wget -qO clickhouse-jdbc-all.jar \
-              https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/${CLICKHOUSE_JDBC_VERSION}/clickhouse-jdbc-${CLICKHOUSE_JDBC_VERSION}-all.jar
-
-            # (необязательно) если понадобятся отдельные httpclient/httpcore, их можно загрузить так же:
-            # wget -qO httpclient5.jar https://repo1.maven.org/.../httpclient5-5.1.3.jar
-            # wget -qO httpcore5.jar  https://repo1.maven.org/.../httpcore5-5.1.3.jar
-          '''
+    stages {
+        stage('Start Services') {
+            steps {
+                sh 'docker-compose up -d'
+                sh 'sleep 15'
+            }
         }
-      }
+
+        stage('Init MySQL') {
+            steps {
+                // Исправлен путь к контейнеру и к файлу
+                sh '''
+                    if docker ps --format '{{.Names}}' | grep -q "project-mysql-1"; then
+                      docker exec project-mysql-1 sh -c 'mysql -uroot -proot bank < /sql/init_mysql.sql'
+                    else
+                      echo "MySQL container not found, skipping init"
+                    fi
+                '''
+            }
+        }
+
+        stage('Register Debezium Connector') {
+            steps {
+                sh '''
+                    echo "Registering Debezium Connector..."
+                    curl -i -X POST http://localhost:8083/connectors \\
+                        -H "Content-Type: application/json" \\
+                        --data-binary @debezium-connector.json || true
+                '''
+            }
+        }
+
+        stage('Prepare JARs') {
+            steps {
+                sh '''
+                    # Скачиваем JDBC-all, если его нет
+                    if [ ! -f "${JDBC_JAR}" ]; then
+                      wget https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.6.0-patch20/clickhouse-jdbc-0.6.0-patch20-all.jar \
+                        -O ${JDBC_JAR}
+                    fi
+                '''
+            }
+        }
+
+        stage('Create ClickHouse Views') {
+            steps {
+                sh '''
+                    if docker ps --format '{{.Names}}' | grep -q "clickhouse-server"; then
+                      docker exec clickhouse-server clickhouse-client \
+                        --user=custom_user --password=0000 \
+                        --query="CREATE DATABASE IF NOT EXISTS default;"
+                    else
+                      echo "ClickHouse container not found, skipping DB creation"
+                    fi
+                '''
+            }
+        }
+
+        stage('Run Spark Job') {
+            steps {
+                // Используем SPARK_HOME из env
+                sh '''
+                    echo "Running Spark job..."
+                    ${SPARK_HOME}/spark-submit \
+                      --jars ${JDBC_JAR} \
+                      --master local[1] \
+                      etl/kafka_to_clickhouse.py
+                '''
+            }
+        }
     }
 
-    stage('Create ClickHouse DB') {
-      steps {
-        sh '''
-          docker exec clickhouse-server \
-            clickhouse-client --user=custom_user --password=0000 \
-            --query="CREATE DATABASE IF NOT EXISTS default;"
-        '''
-      }
+    post {
+        always {
+            // Останавливаем и очищаем контейнеры, удаляем volume
+            sh '''
+                docker-compose down -v
+            '''
+        }
     }
-
-    stage('Run Spark Job') {
-      steps {
-        sh """
-          ${SPARK_HOME:-/opt/homebrew/bin}/spark-submit \
-            --master local[1] \
-            --packages org.apache.spark:spark-sql-kafka-0-10_${SCALA_VERSION}:${SPARK_VERSION} \
-            --jars ${WORKDIR}/clickhouse-jdbc-all.jar \
-            etl/kafka_to_clickhouse.py
-        """
-      }
-    }
-  }
-
-  post {
-    always {
-      sh 'docker-compose down -v'
-    }
-  }
 }
